export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";

export const LOAD_FAVOURITES_REQUEST = "LOAD_FAVOURITES_REQUEST";
export const LOAD_FAVOURITES_SUCCESS = "LOAD_FAVOURITES_SUCCESS";
export const LOAD_FAVOURITES_FAIL = "LOAD_FAVOURITES_FAIL";

export const CLEAR_FAVOURITES = "CLEAR_FAVOURITES";